### PR TITLE
Update 3.sysmon.conf

### PR DESCRIPTION
**Pull request by MikeKemmerer**
Added support for Event ID 10.
Updated hash field extraction to support multiple hash types.

### CODE REVIEW

**Comment by MikeKemmerer** [comment]
Added EventID 10 support. Calling it Object=Process Action=Read. 
Adding support for all of the hash types with minimal configuration changes needed on the analytic side, I hope.

**Comment by infosec-alchemist** [comment]
Looks great!  Thanks for the add

**Comment by MikeKemmerer** [comment]
except, I made a mistake and lost track of curly braces, the grok I added needs to drop below the closing one.

**Comment by infosec-alchemist** [comment]
do you want to fix it and resubmit?

**Pull request merged**
